name: Deploy

on:
  push:
    branches:
      #- main
       - cf
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:   # 允许手动触发
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: yarn install   
    - run: yarn build
      env:
        NODE_ENV: production
    - name: Prepare KV namespace
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      run: |
        npm install -g wrangler
        KV_EXIST=$(wrangler kv namespace list | grep "KV_STATUS_PAGE" || true)
        if [ -z "$KV_EXIST" ];then
          echo "KV命名空间不存在，开始创建"
          wrangler kv namespace create KV_STATUS_PAGE --env production
        else
          echo "KV命名空间已存在，跳过创建"
        fi
        
        echo "=== 正在获取 wrangler kv namespace list 的原始内容 ==="
        RAW_ALL=$(wrangler kv namespace list --env production)
        echo "$RAW_ALL"
        echo "=== 原始内容打印完毕 ==="

        # 截取：只保留第一个 [ 之后的内容，重组纯净JSON
        RAW_JSON=$(echo "$RAW_ALL" | sed -n '/^\[/,/^]/p')
        echo "=== 清洗后的 wrangler kv namespace list 的内容 ==="
        echo "$RAW_ALL"
        echo "=== 清晰后的内容打印完毕 ==="
        
        KV_NAMESPACE_ID=$(echo "$RAW_JSON" | jq -r '.[] | select(.title=="production-KV_STATUS_PAGE") | .id')
        echo "KV_NAMESPACE_ID = >${KV_NAMESPACE_ID}<"
        
        if [ -z "$KV_NAMESPACE_ID" ];then
          echo "ERROR: 获取KV ID失败"
          exit 1
        fi
        sed -i 's/KV_ID_PLACEHOLDER/'"${KV_NAMESPACE_ID}"'/g' wrangler.toml
        cat wrangler.toml
        [ -z "$SECRET_SLACK_WEBHOOK_URL" ] && SECRET_SLACK_WEBHOOK_URL="default-gh-action-secret" || true
        [ -z "$SECRET_TELEGRAM_API_TOKEN" ] && SECRET_TELEGRAM_API_TOKEN="default-gh-action-secret" || true
        [ -z "$SECRET_TELEGRAM_CHAT_ID" ] && SECRET_TELEGRAM_CHAT_ID="default-gh-action-secret" || true
        [ -z "$SECRET_DISCORD_WEBHOOK_URL" ] && SECRET_DISCORD_WEBHOOK_URL="default-gh-action-secret" || true
    - name: Publish to Cloudflare Workers
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        SECRET_SLACK_WEBHOOK_URL: ${{ secrets.SECRET_SLACK_WEBHOOK_URL }}
        SECRET_TELEGRAM_API_TOKEN: ${{ secrets.SECRET_TELEGRAM_API_TOKEN }}
        SECRET_TELEGRAM_CHAT_ID: ${{ secrets.SECRET_TELEGRAM_CHAT_ID }}
        SECRET_DISCORD_WEBHOOK_URL: ${{ secrets.SECRET_DISCORD_WEBHOOK_URL }}
      run: |
        npx wrangler deploy --env production
    - name: Post kv-gc
      run: yarn kv-gc
