name: Deploy

on:
  push:
    branches:
      #- main
       - cloudflare
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:   # 允许手动触发
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: yarn install
    - run: yarn build
      env:
        NODE_ENV: production
    - name: Prepare KV namespace
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      run: |
        npm install -g wrangler
        wrangler kv namespace create KV_STATUS_PAGE --env production || true
        wrangler kv namespace list --json > kv_list.json
        cat kv_list.json
        export KV_NAMESPACE_ID=$(node -pe "const list=JSON.parse(fs.readFileSync('kv_list.json'));const item=list.find(x=>x.title.includes('KV_STATUS_PAGE'));item?item.id:''")
        echo "KV_NAMESPACE_ID = >${KV_NAMESPACE_ID}<"
        if [ -z "$KV_NAMESPACE_ID" ];then
          echo "ERROR: KV_NAMESPACE_ID 为空，获取KV命名空间失败"
          exit 1
        fi
        sed -i 's/KV_ID_PLACEHOLDER/'"${KV_NAMESPACE_ID}"'/g' wrangler.toml
        cat wrangler.toml
        [ -z "$SECRET_SLACK_WEBHOOK_URL" ] && SECRET_SLACK_WEBHOOK_URL="default-gh-action-secret" || true
        [ -z "$SECRET_TELEGRAM_API_TOKEN" ] && SECRET_TELEGRAM_API_TOKEN="default-gh-action-secret" || true
        [ -z "$SECRET_TELEGRAM_CHAT_ID" ] && SECRET_TELEGRAM_CHAT_ID="default-gh-action-secret" || true
        [ -z "$SECRET_DISCORD_WEBHOOK_URL" ] && SECRET_DISCORD_WEBHOOK_URL="default-gh-action-secret" || true
    - name: Publish to Cloudflare Workers
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        environment: production
      env:
        SECRET_SLACK_WEBHOOK_URL: ${{secrets.SECRET_SLACK_WEBHOOK_URL}}
        SECRET_TELEGRAM_API_TOKEN: ${{secrets.SECRET_TELEGRAM_API_TOKEN}}
        SECRET_TELEGRAM_CHAT_ID: ${{secrets.SECRET_TELEGRAM_CHAT_ID}}
        SECRET_DISCORD_WEBHOOK_URL: ${{secrets.SECRET_DISCORD_WEBHOOK_URL}}
    - name: Post kv-gc
      run: yarn kv-gc
